const {test}=require('node:test');const assert=require('node:assert/strict');const C=require('../learning-core_v0.0.1.js');
const words=C.canonicalize([{id:1,word:'book',meaning:'책',level:'초등기본'},{id:2,word:'book',meaning:'책',level:'중등기본'},{id:3,word:'book',meaning:'예약하다',level:'고등기본'},{id:4,word:'apple',meaning:'사과',level:'초등기본'}]);
test('same word and meaning share identity, different meaning does not',()=>{assert.equal(words[0].key,words[1].key);assert.notEqual(words[0].key,words[2].key);assert.equal(C.unique(words).length,3);});
test('HTML escaping covers attribute delimiters',()=>assert.equal(C.esc('<"\'&>'),'&lt;&quot;&#39;&amp;&gt;'));
test('one day never reports mastery',()=>assert.equal(C.remembered({e2k:{days:1}}),false));
test('three recall days reports meaning mastery',()=>assert.equal(C.knowsMeaning({e2k:{days:3}}),true));
test('spelling mastery is independent of meaning',()=>{assert(C.knowsSpelling({k2e:{days:3}}));assert(!C.knowsMeaning({k2e:{days:3}}));});
test('MCQ alone does not claim recall mastery',()=>assert(!C.remembered({mcq:{days:50}})));
test('legacy record remains studied without inflated mastery',()=>{const r=C.recordFor(words[0],{},[{word:'book',level:'초등기본',learning:{}}],words);assert.equal(r.seen,1);assert(!C.remembered(r));});
test('changed meaning invalidates old mastery',()=>assert.deepEqual(C.recordFor(words[0],{'1':{meaning:'예약하다',seen:99,e2k:{days:3}}}),{}));
test('dashboard partitions all words once',()=>{const s=C.summary(words,{'1':{meaning:'책',seen:4,e2k:{days:3},due_at:'2020-01-01'}},[],words);assert.equal(s.total,3);assert.equal(s.unseen+s.learning+s.known,3);assert.equal(s.known,1);});
test('future review excluded, overdue included',()=>{assert(!C.due({seen:1,due_at:'2100-01-01'}));assert(C.due({seen:1,due_at:'2020-01-01'}));});
test('daily plan never includes duplicate canonical words',()=>{const p=C.plan(words,{},[],words,30,10);assert.equal(p.all.length,3);});
test('daily plan separates fresh from overdue',()=>{const p=C.plan(words,{'1':{meaning:'책',seen:1,due_at:'2020-01-01'}},[],words,2,1);assert.equal(p.reviews.length,1);assert.equal(p.fresh.length,2);});
test('distractor meanings are unique',()=>{const o=C.options(words[0],words,10);assert.equal(o.length,new Set(o).size);assert.equal(o.filter(x=>x==='책').length,1);});
test('English case and spaces normalize',()=>assert(C.checkEnglish(' TAKE   A break ','take a break')));
test('Korean negation does not match by substring',()=>assert(!C.checkKorean('사과가 아니다','사과')));
test('Korean synonyms separated with semicolons accepted',()=>assert(C.checkKorean('대답하다','대답; 답; 대답하다')));
test('CSV quoted commas, CRLF, escaped quote and multiline',()=>{const r=C.parseDelimited('\uFEFFword,meaning,level,example\r\nbook,"책, 도서",초등기본,"a ""book""\nnext"');assert.equal(r[0].meaning,'책, 도서');assert.equal(r[0].example,'a "book"\nnext');});
test('Excel paste accepts Korean headers',()=>assert.equal(C.parseDelimited('단어\t뜻\t난이도\ncat\t고양이\t초등기본')[0].word,'cat'));
test('malformed CSV and duplicate columns rejected',()=>{assert.throws(()=>C.parseDelimited('word,meaning,level\n"cat,고양이,초등기본'));assert.throws(()=>C.parseDelimited('word,단어,meaning,level\na,a,b,c'));});
test('preview identifies additions and meaning edits',()=>{const p=C.previewImport([{word:'book',meaning:'도서',level:'초등기본'},{word:'cat',meaning:'고양이',level:'초등기본'}],words);assert.equal(p[0].action,'수정');assert.equal(p[1].action,'추가');assert.equal(p[0].id,1);assert(p[0].expected);});
test('preview preserves optional existing metadata',()=>{const p=C.previewImport([{word:'book',meaning:'책',level:'초등기본'}],[{...words[0],example:'A book.',pos:'명사'}]);assert.equal(p[0].example,'A book.');assert.equal(p[0].action,'동일');});
test('ambiguous import requires id',()=>assert.throws(()=>C.previewImport([{word:'book',meaning:'책',level:'초등기본'}],[words[0],{...words[0],id:9}])));
test('id cannot silently change word or level',()=>assert.throws(()=>C.previewImport([{id:1,word:'cat',meaning:'고양이',level:'초등기본'}],words)));
test('duplicate import rows rejected',()=>assert.throws(()=>C.previewImport([{word:'cat',meaning:'고양이',level:'초등기본'},{word:'cat',meaning:'고양이',level:'초등기본'}],words)));
test('export parses back without metadata loss',()=>{const r=C.parseDelimited(C.csv([{id:1,word:'book',meaning:'책, 도서',level:'초등기본',example:'A "book".'}]));assert.equal(r[0].example,'A "book".');});
test('supplement is unique and has original examples',()=>{const rows=require('../supplement_v0.0.1.json');assert.equal(rows.length,60);assert.equal(new Set(rows.map(r=>r.word)).size,60);assert(rows.every(r=>r.example&&r.translation&&C.LEVELS.includes(r.level)));});
