const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const C=require('../learning-core_v0.0.1.js');
const source=fs.readFileSync(require.resolve('../app_v0.0.6.js'),'utf8').split('(async()=>{try{if(DEMO)initDemo();')[0];
function app(){
 const events={},storage=new Map(),node={innerHTML:'',focus(){},showModal(){this.open=true;},querySelector(){return {focus(){}}},addEventListener:(k,v)=>events[k]=v};
 const ctx=vm.createContext({window:{WM:C,addEventListener(){}},document:{getElementById:()=>node},location:{search:'?demo=1'},URLSearchParams,localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v)},crypto:{randomUUID:()=> 'test'},setTimeout,clearTimeout});
 vm.runInContext(source,ctx);vm.runInContext("user={id:'one'};words=C.canonicalize(Array.from({length:9},(_,i)=>({id:i+1,word:'word'+i,meaning:'뜻'+i,level:'초등기본',example:'Example',translation:'예문'})));",ctx);
 return {run:s=>vm.runInContext(s,ctx),events,node,storage};
}
test('choice count defaults to six and offers only four, six and eight',()=>{const a=app();assert.equal(a.run('choiceCount()'),6);a.run('today();');assert.equal(a.run('quiz.settings.mcqOptionCount'),6);assert.match(a.run('choiceOptions()'),/value="6" selected/);assert.doesNotMatch(a.run('choiceOptions()'),/value="10"/);});
test('choice preference shared across setup and today, isolated between profiles',async()=>{const a=app();for(const n of [4,6,8]){await a.events.change({target:{id:'setup-options',value:String(n)}});a.run('today();startQuiz(quiz.planned,quiz.settings);');assert.equal(a.run('quiz.options.length'),n);}a.run("user={id:'two'};");assert.equal(a.run('choiceCount()'),6);a.run("user={id:'one'};");assert.equal(a.run('choiceCount()'),8);});
test('correct answer opens modal with fixed-footer action, example disclosure, and last-question label',()=>{const a=app();a.run("startQuiz(words.slice(0,1),{questionType:'mcq',mcqOptionCount:6});answered(true);");assert.equal(a.node.open,true);assert.match(a.node.innerHTML,/<dialog[^>]+aria-labelledby="feedback-title"/);assert.match(a.node.innerHTML,/확인 · 학습 결과 보기/);assert.match(a.node.innerHTML,/<details/);assert.match(a.node.innerHTML,/class="dialog-footer"/);assert.equal(a.run('quiz.results.length'),1);let prevented=false;a.node.oncancel({preventDefault(){prevented=true;}});assert.equal(prevented,true);});
test('wrong answer requeues and immediate confirmation cannot skip feedback',async()=>{const a=app();a.run("startQuiz(words.slice(0,1),{questionType:'mcq',mcqOptionCount:6});answered(false);quiz.feedbackReadyAt=Date.now()+100000;");assert.match(a.node.innerHTML,/확인 · 다음 문제/);await a.run("action('next');");assert.equal(a.run('quiz.answered'),true);assert.equal(a.run('quiz.results.length'),1);await a.run("quiz.feedbackReadyAt=0;action('next');");assert.equal(a.run('quiz.current.requeued'),true);assert.equal(a.run('quiz.answered'),false);});
test('ungraded AI fallback also uses dialog without recording a wrong answer',()=>{const a=app();a.run("startQuiz(words.slice(0,1),{questionType:'e2k',mcqOptionCount:6});reveal();");assert.match(a.node.innerHTML,/이번 답은 채점하지 않았어요/);assert.equal(a.run('quiz.results.length'),0);assert.equal(a.run('quiz.queue.length'),1);});
